version: '3.8'

services:
  app:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - '.env'
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
      - celery_worker

  db:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - '.env'
    ports:
      - '3306:3306'

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    entrypoint: celery
    command: -A like_soft worker -l info
    depends_on:
      - redis

volumes:
  mysql_data:
